### ISSUE TITLE
최초 make init 시 ssl 관련 ansible 오류

### ISSUE THREAD

**Issue by riceluxs1t** [jongman/algospot#113]
![screen shot 2017-01-18 at 1 37 10 am](https://cloud.githubusercontent.com/assets/10087079/22055089/e512222a-dd1e-11e6-9f8c-8eeb71c4e2fd.png)

아마 개인 개발 환경의 문제라 생각하지만 (ssl 관련) 제 맥북에 설치 시 위와 같은 에러를 뻗고 죽었습니다.
다행히 suggest 하는 데로 ansible playbook 을 아래와 같이 간단히 수정하면 돕니다.

![screen shot 2017-01-18 at 1 40 33 am](https://cloud.githubusercontent.com/assets/10087079/22055121/25d03360-dd1f-11e6-8dad-e673ee30ef85.png)

@hhjeong

**Comment by wookayin** [comment]
github.com에 SSL로 접근하는데 certificate error가 나는 것은 일반적인 상황은 아닌것으로 보입니다. 
suggest해주신 패치는 좋은 workaround로 보이네요~ 다만 SSL error는 인증서 관련 문제를 해결하는 방향이 더 좋다고 생각됩니다..^^;

**Comment by riceluxs1t** [comment]
안녕하세요. 컴파일러가 노려보면 알아서 오류를 고친다는 "욱신" 님께서 이런 자잘한 이슈에 답글을 달아주시다니..감사합니다. 

네 말씀해주신 것 처럼, 개인 컴퓨터 셋업의 문제같습니다. 정확한 문제 진단이 필요하겠지만 개인 컴퓨터 셋업에 따라 셋업이 실패 할 수도 있다면 READ.ME에 한줄 추가 정도는 바람직 하지 않을까 생각합니다. 

저 단계에서 실패하면 가상 머신 설치까지는 완료되지만, ansible 스크립트가 가상머신에 아무것도 설치하지 않게되어 혹시라도 ansible 을 잘모르거나 할 경우 셋업에 시간이 많이 걸릴 것 같습니다.

**Comment by wookayin** [comment]
네, contribution 감사합니다!
Closing via #116.
