### ISSUE TITLE
마크다운 문법 수정 및 각종 휴리스틱 추가

### ISSUE THREAD

**Issue by wookayin** [jongman/algospot#81]
* Heading 1 은 `#` prefix 뒤에 공백이 와야 하는 것으로 (#include 방지)

**Comment by beingryu** [comment]
#include는 아예 허용을 안했으면 합니당 ㅠㅠ

**Comment by jongman** [comment]
`#include`를 따로 막으려다가 어차피 그러면 `#define`도 막아야 하고, 미사카? 선다운? 에 옵션이 있길래 그리 하였음 ~_~
