### ISSUE TITLE
ACE 끌 수 있는 버튼 만들기

### ISSUE THREAD

**Issue by jongman** [jongman/algospot#84]
기본 에디터 사용 / ACE 에디터 사용 으로 토글되는 버튼이 있으면 좋을 듯. 모바일 등 ACE가 골치아픈 환경이 좀 있는 듯..

**Comment by wookayin** [comment]
흠 요즘 시대에 이런거 고민 안하고 짠! PROFIT!! 할수 있는 멋진 에디터가 있을법도 한데요... 나중에 찾아봐야겠음 ㅠ

**Comment by beingryu** [comment]
제가 최근에 이걸 직접적으로 찾아본 건 아니고 online collaborative editor들을 찾아봤을 땐 다 Ace 기반이긴
했습니다 ㅜㅜ

**Comment by jongman** [comment]
요즘 출퇴근길에 알고스팟에 질문 답변좀 달아보려 했더니 아주 그냥 [데스나이트](https://namu.wiki/w/%EB%8D%B0%EC%8A%A4%20%EB%82%98%EC%9D%B4%ED%8A%B8#s-5) 되것네...

테스트 해보니까 codemirror 에는 이런 문제가 없는 것 같아서 이걸 해볼까 생각중

**Comment by jongman** [comment]
codemirror 로 바꿨음
