### ISSUE TITLE
문제 추가할 때 데이터 여러개 업로드

### ISSUE THREAD

**Issue by Baekjoon** [jongman/algospot#94]
데이터가 100개인 문제를 하나 만들고 업로드를 해보았으나, 한 번에 전체를 업로드 할 수 없었습니다.

또, 일일이 하나씩 클릭을 해서 업로드하던 중 일정 개수 (정확하게 몇 개인진 기억이 안나지만 67번 데이터 out 파일을 올릴때 쯤이니 약 134번째?) 를 넘어가면 더이상 데이터가 올라가질 않았습니다.

**Comment by Baekjoon** [comment]
https://algospot.com/judge/problem/read/BOJ 이 문제 데이터 업로드하다가 생긴일

**Comment by jongman** [comment]
zip 파일 업로드 되는데... 눙물이... ㅠ

On Tuesday, August 4, 2015, Baekjoon Choi <notifications@github.com> wrote:

> https://algospot.com/judge/problem/read/BOJ 이 문제 데이터 업로드하다가 생긴일
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jongman/algospot/issues/94#issuecomment-127509283>.
>


-- 

JongMan

**Comment by Baekjoon** [comment]
어..? 어..... 아.... ㅠㅠㅠ
